services:
  - type: web
    name: fist-gym-app
    env: node
    plan: free
    buildCommand: npm install && npm run build && cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: OPENAI_API_KEY
        sync: false
